"use client";

import { useState } from "react";
import ResponsiveModal from "@/components/ui/ResponsiveModal";
import Button from "@/components/ui/Button";
import { FileCheck, Loader2, X } from "lucide-react";
import { runAIDetector } from "@/services/aiAnalysis.service";
import toast from "react-hot-toast";
import { useQueryClient } from "@tanstack/react-query";

interface RunAIDetectorModalProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  documentId: string;
  fileName: string;
}

export default function RunAIDetectorModal({
  isOpen,
  onOpenChange,
  documentId,
  fileName,
}: RunAIDetectorModalProps) {
  const [prompt, setPrompt] = useState("");
  const [isRunning, setIsRunning] = useState(false);
  const queryClient = useQueryClient();

  const handleRun = async () => {
    if (!prompt.trim()) {
      toast.error("Please enter a prompt");
      return;
    }

    setIsRunning(true);
    try {
      const result = await runAIDetector({
        documentId,
        prompt: prompt.trim(),
      });
      console.log(result, "result");
      toast.success("AI Content Detector started successfully!");
      queryClient.invalidateQueries({ queryKey: ["ai-analysis-results"] });
      queryClient.invalidateQueries({
        queryKey: ["ai-content-detector-results"],
      });
      queryClient.invalidateQueries({ queryKey: ["user-documents"] });
      queryClient.invalidateQueries({ queryKey: ["ai-analysis-stats"] });
      onOpenChange(false);
      setPrompt("");
    } catch (error: any) {
      toast.error(
        error?.response?.data?.message || "Failed to start AI Content Detector"
      );
    } finally {
      setIsRunning(false);
    }
  };

  return (
    <ResponsiveModal
      isOpen={isOpen}
      onOpenChange={onOpenChange}
      title="Run AI Content Detector"
    >
      <div className="bg-[#FDFDFD] w-full min-w-0 sm:min-w-[551px] max-h-screen overflow-y-scroll scrollbar-hide p-6 sm:p-10 rounded-[27px] flex flex-col">
        {/* Header */}
        <div className="flex flex-row justify-between mb-6">
          <div className="flex flex-col gap-1.5">
            <p className="text-xl text-[#0c0c0c] font-medium">
              Run AI Content Detector
            </p>
            <p className="text-base font-normal text-[#717171]">
              Detect AI-generated content in {fileName}
            </p>
          </div>
          <div onClick={() => onOpenChange(false)}>
            <X
              width={22}
              height={22}
              className="text-[#000000] cursor-pointer"
            />
          </div>
        </div>

        <div className="flex flex-col space-y-6">
          {/* Prompt Input */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-700">
              Prompt <span className="text-red-500">*</span>
            </label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="Enter instructions for AI detection (e.g., 'Detect if this document was generated by AI. Check for patterns typical of AI writing')"
              className="w-full min-h-[120px] px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent resize-none"
              disabled={isRunning}
            />
            <p className="text-xs text-gray-500">
              Provide clear instructions for how the AI should detect content
            </p>
          </div>

          {/* Generate Button */}
          <Button
            onClick={handleRun}
            disabled={isRunning || !prompt.trim()}
            className="w-full"
            variant="primary"
          >
            {isRunning ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <FileCheck className="w-4 h-4 mr-2" />
                Generate AI Detection
              </>
            )}
          </Button>
        </div>
      </div>
    </ResponsiveModal>
  );
}
